In [2]:
import numpy as np

In [4]:
arr = np.array([1, 3, 4])

In [6]:
arr

array([1, 3, 4])

In [7]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((4, 6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(1, 100, 7)

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [14]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [16]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [17]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [18]:
myarr.shape

(4, 3)

In [20]:
myarr.size

12

In [21]:
myarr.ndim

2

In [23]:
myarr.dtype

dtype('int64')

In [24]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]], 
dtype = 'float32')

In [26]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [30]:
n = myarr.astype('float64')

In [31]:
n.dtype

dtype('float64')

In [32]:
reshape = myarr.reshape((3, 4))

In [34]:
reshape

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., 13.]], dtype=float32)

In [36]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [37]:
myarr.reshape((2, 6))

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 11., 12., 13.]], dtype=float32)

In [38]:
myarr.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.],
      dtype=float32)