In [2]:
import numpy as np

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [8]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [9]:
flat = arr.flatten()

In [10]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
flat[0]

np.int64(1)

In [12]:
flat[3: 6]

array([4, 5, 6])

In [13]:
flat[:5] # same as flat[0, 5]

array([1, 2, 3, 4, 5])

In [14]:
flat[3:] # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [15]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [35]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [36]:
b = flat[3:7].copy() # this is not a slice because we are using copy method to get the copy

In [37]:
b

array([444444,      5,      6,      7])

In [38]:
b[0] = 4444434535

In [39]:
b

array([4444434535,          5,          6,          7])

In [41]:
arr = np.array([1, 54, 23, 53, 2, 3 ,34 ,5, 6])

In [42]:
arr[[1, 4, 6]]

array([54,  2, 34])